import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

def plot_single_run(history):
    fig, ax = plt.subplots()
    ax.plot(history['day'], history['s'], label='Susceptible Population')
    ax.plot(history['day'], history['i'], label='Infected Population')
    ax.plot(history['day'], history['r'], label='Recovered Population')
    ax.set_xlabel("Days")
    ax.set_ylabel("Agents")
    ax.legend()

def plot_mc_uncert(curves_array,n_agents):
    fig, ax = plt.subplots()
    pct = (curves_array/n_agents)*100
    days = np.arange(pct.shape[1])
    for curve in pct:
        ax.plot(days, curve, alpha = 0.05)
    median = np.percentile(pct, 50, axis=0)
    lower = np.percentile(pct, 2.5, axis=0)
    upper = np.percentile(pct, 97.5, axis=0)
    ax.fill_between(days, lower, upper, alpha=0.2, label='95% CI')
    ax.plot(days, median, lw=2.5,label='Median infected %')
    ax.set_xlabel("Day"); ax.set_ylabel("% Population infected")
    ax.set_title("Monte Carlo uncertainty bands", fontweight='bold')
    ax.legend()
    plt.show()
    
def plot_outcome_dist(df):
    fig, axes = plt.subplots(1, 3)
    for ax, (col, label) in zip(axes, [('peak_infected_pct', 'Peak infected (%)'), ('attack_rate_pct', 'Attack rate (%)'), ('peak_day', 'Day of peak')]):
        ax.hist(df[col], bins=25, edgecolor='white', alpha=0.85)
        ax.axvline(df[col].median(), color='black', linestyle='--', label=f'Median: {df[col].median():.1f}')
        ax.set_xlabel(label)
        ax.set_ylabel("Runs")
        ax.set_title(label, fontweight='bold')
        ax.legend()
        
    fig.suptitle("Monte Carlo outcome distributions ")
    plt.show()
    

#################################################
#### The part below is generated by ClaudeAI ####
#################################################

def animate_epidemic(model_history, agents, grid_size, filename="epidemic.gif"):

    snapshots = model_history.get('snapshots', model_history.get('snapshot', None))
    if snapshots is None:
        print("No snapshots found in history — check model._record()")
        return

    days = model_history['day']
    s_series = model_history['s']
    i_series = model_history['i']
    r_series = model_history['r']
    n_agents = len(agents)
    n_days = len(days)

    fig, (ax_grid, ax_curve) = plt.subplots(1, 2, figsize=(12, 5))
    fig.patch.set_facecolor('#0f172a')
    for ax in [ax_grid, ax_curve]:
        ax.set_facecolor('#1e293b')
        ax.tick_params(colors='white')
        for spine in ax.spines.values():
            spine.set_edgecolor('#334155')

    color = {'s': '#378ADD', 'i': '#E24B4A', 'r': '#4CAF50'}

    # --- Grid setup ---
    ax_grid.set_xlim(-1, grid_size)
    ax_grid.set_ylim(-1, grid_size)
    ax_grid.set_aspect('equal')
    ax_grid.set_xticks([])
    ax_grid.set_yticks([])

    # --- Curve setup ---
    ax_curve.set_xlim(0, n_days)
    ax_curve.set_ylim(0, n_agents * 1.05)
    ax_curve.set_xlabel("Day", color='white')
    ax_curve.set_ylabel("Agents", color='white')

    line_s, = ax_curve.plot([], [], color=color['s'], lw=2, label='Susceptible')
    line_i, = ax_curve.plot([], [], color=color['i'], lw=2, label='Infected')
    line_r, = ax_curve.plot([], [], color=color['r'], lw=2, label='Recovered')
    ax_curve.legend(loc='upper right', fontsize=9,
                    facecolor='#1e293b', labelcolor='white', framealpha=0.8)

    def update(frame):
        # --- Clear and redraw grid every frame ---
        ax_grid.cla()
        ax_grid.set_facecolor('#1e293b')
        ax_grid.set_xlim(-1, grid_size)
        ax_grid.set_ylim(-1, grid_size)
        ax_grid.set_aspect('equal')
        ax_grid.set_xticks([])
        ax_grid.set_yticks([])
        ax_grid.set_title(f"Day {days[frame]}", color='white', fontsize=12)
        for spine in ax_grid.spines.values():
            spine.set_edgecolor('#334155')

        snap = snapshots[frame]
        for key, label in [('s', 'S'), ('i', 'I'), ('r', 'R')]:
            pts = snap[key]
            if pts:
                xs, ys = zip(*pts)
                size = 18 if key == 'i' else 12
                ax_grid.scatter(xs, ys, s=size, c=color[key],
                                alpha=1.0 if key == 'i' else 0.7,
                                label=label)

        ax_grid.legend(loc='upper right', fontsize=9,
                       facecolor='#1e293b', labelcolor='white', framealpha=0.8)

        # --- Update SIR curve ---
        line_s.set_data(days[:frame+1], s_series[:frame+1])
        line_i.set_data(days[:frame+1], i_series[:frame+1])
        line_r.set_data(days[:frame+1], r_series[:frame+1])

    ani = animation.FuncAnimation(
        fig, update, frames=n_days,
        interval=80, blit=False
    )

    print("Saving GIF — this takes a minute...")
    ani.save(filename, writer='pillow', fps=15, dpi=90)
    print(f"Saved: {filename}")
    plt.close()
def plot_evolution(history):
  fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
  days = history['day']

  # mean infectivity drift
  ax1.plot(days, history['mean_inf'], color='#E24B4A', lw=2)
  ax1.set_xlabel("Day")
  ax1.set_ylabel("Mean infectivity")
  ax1.set_title("Viral evolution — infectivity drift", fontweight='bold')

  # overlay infected count for context
  ax1b = ax1.twinx()
  ax1b.fill_between(days, history['i'], alpha=0.08, color='grey')
  ax1b.set_ylabel("Infected", color='grey', fontsize=9)
  ax1b.tick_params(colors='grey')

  # SIR curve alongside
  ax2.plot(days, history['s'], color='#378ADD', lw=2, label='Susceptible')
  ax2.plot(days, history['i'], color='#E24B4A', lw=2, label='Infected')
  ax2.plot(days, history['r'], color='#639922', lw=2, label='Recovered')
  ax2.set_xlabel("Day")
  ax2.set_ylabel("Agents")
  ax2.set_title("SIR curve", fontweight='bold')
  ax2.legend()

  plt.tight_layout()
  plt.savefig("evolution.png", dpi=150)
  plt.show()